# docker-compose -f docker-compose.yml build

# docker-compose -f docker-compose.yml up -d
# docker-compose -f docker-compose.yml stop

version: '3'

services:
  yfhs-mysql:
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./init-files/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    container_name: yfhs-mysql

  yfhs-pma:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    links:
        - yfhs-mysql:db
    ports:
        - 8080:80
    container_name: yfhs-pma
