# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('conversation', models.IntegerField()),
                ('review', models.IntegerField()),
                ('style', models.IntegerField()),
                ('satisfaction', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('review_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=200)),
                ('worker_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
